title: <p align="center"> Huong (Hanna) Nguyen </p>
logo: "/images/profile1.png?raw=true"
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/huonghs/">LinkedIn</a> |
  <a href="https://www.linkedin.com/in/huonghs/">Resume</a> |
  <a href="https://github.com/huonghs">Github</a> 
  </p>
  
  <p align="center">
  Hello! This is Hanna. I am a highly analytical professional with strong and in-depth experience in Marketing Science, Marketing Analytics and Programmatic AdTech landscape.
  
 <br><br>
  Currently, I am a marketing analyst @ Audigent, and a candidate in MS Statistics (Data Science) @ Baruch. 
  I'm passionate about translating data into valuable and comprehensible insights using machine learning and statistical methods.  
  </p>
  

theme: jekyll-theme-minimal
timezone: America/New_York
future: true
