title: <p align="center"> Huong (Hanna) Nguyen </p>
logo: "/images/profile2.png?raw=true"
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/huonghs/">LinkedIn</a> |
  <a href="https://drive.google.com/file/d/121lHOWiq_CiQllTtJYZ-bjiJE8-rRir1/view?usp=sharing">Resume</a> |
  <a href="https://github.com/huonghs">Github</a> 
  </p>
  
  <p align="center">
  Hello! This is Hanna!
  
  <br><br>
  I am an analytical-oriented professional with in-depth experience in AdTech, Ad Monetization, and the Media Streaming Industry.
  I translate data into valuable and comprehensible insights using data science, machine learning, and statistical methods.  
 
 <br><br>

  </p>
  

theme: jekyll-theme-minimal
timezone: America/New_York
future: true
