title: <p align="center"> Huong (Hanna) Nguyen </p>
logo: "/images/profile1.png?raw=true"
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/huonghs/">LinkedIn</a> |
  <a href="https://www.linkedin.com/in/huonghs/">Resume</a> |
  <a href="https://github.com/huonghs">Github</a> 
  </p>
  
  <p align="left">
  Hello! This is Hanna!
  
  <br><br>
  I am a highly analytical professional with in-depth experience in Marketing Science and Programmatic AdTech landscape, with a passion and curiorsity to translate data into valuable and comprehensible insights using machine learning and statistical methods.  
 
 <br><br>
  Currently, I am a marketing analyst @ Audigent, and a candidate in MS Statistics (Data Science) @ Baruch, NYC. 
  
  </p>
  

theme: jekyll-theme-minimal
timezone: America/New_York
future: true
